/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/auth/logout/ — revoke the refresh token and clear its cookie.
         *
         *     Reads the refresh token from the httpOnly cookie, blacklists it so it can no
         *     longer mint access tokens, and clears the cookie. Idempotent: a missing or
         *     already-invalid cookie still succeeds (there is nothing left to revoke).
         *     Access tokens already issued remain valid until they expire (minutes); there
         *     is no server-side access-token revocation.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/auth/me/ — the authenticated caller's own user record. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/auth/register/ — open self-registration, no secret required.
         *
         *     A brand-new phone creates a User (201). A phone that already exists as a
         *     pre-created, password-less member is activated by setting the password
         *     (200, PRD §3.4). A phone that already has a usable password is rejected (400).
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/auth/token/ — log in with phone + password.
         *
         *     Returns the short-lived access token in the body and sets the ~1-day refresh
         *     token as an httpOnly cookie (never exposed to JavaScript). Wrong credentials
         *     still yield 401 NO_ACTIVE_ACCOUNT.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/auth/token/refresh/ — mint a new access token.
         *
         *     Reads the refresh token from the httpOnly cookie (not the request body).
         *     A missing, invalid, expired, or blacklisted cookie yields 401 TOKEN_NOT_VALID.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bank-transactions/{id}/assign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/bank-transactions/{id}/assign/ and /rematch/ */
        post: operations["bank_transactions_assign_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bank-transactions/{id}/rematch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/bank-transactions/{id}/assign/ and /rematch/ */
        post: operations["bank_transactions_rematch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dues/{id}/reverse-payment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/dues/{id}/reverse-payment/ */
        post: operations["dues_reverse_payment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funds/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `/api/funds/` -- list/create, and `/api/funds/{id}/` -- retrieve/update/delete.
         *
         *     Every action is scoped to funds the caller created: `get_queryset`
         *     (via `FundOwnedQuerySetMixin`) filters the list, and `creator` is
         *     stamped from the request on create, never accepted from the client.
         */
        get: operations["funds_list"];
        put?: never;
        /**
         * @description `/api/funds/` -- list/create, and `/api/funds/{id}/` -- retrieve/update/delete.
         *
         *     Every action is scoped to funds the caller created: `get_queryset`
         *     (via `FundOwnedQuerySetMixin`) filters the list, and `creator` is
         *     stamped from the request on create, never accepted from the client.
         */
        post: operations["funds_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funds/{fund_pk}/bank-transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/POST /api/funds/{fund_pk}/bank-transactions/ */
        get: operations["funds_bank_transactions_list"];
        put?: never;
        /** @description GET/POST /api/funds/{fund_pk}/bank-transactions/ */
        post: operations["funds_bank_transactions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funds/{fund_pk}/bank-transactions/import/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/funds/{fund_pk}/bank-transactions/import/  (multipart)
         *
         *     Accepts a single Excel file under the key ``file``. The file is parsed
         *     and validated, then written in a single all-or-nothing transaction: any
         *     invalid row rejects the whole file with ``400 {imported: 0, errors:
         *     [{row, field, error}]}`` and nothing is written. On success returns
         *     ``201`` with the imported count and the created transactions.
         */
        post: operations["funds_bank_transactions_import_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funds/{fund_pk}/bank-transactions/unmatched/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/POST /api/funds/{fund_pk}/bank-transactions/ */
        get: operations["funds_bank_transactions_unmatched_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funds/{fund_pk}/loans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/POST /api/funds/{fund_pk}/loans/ */
        get: operations["funds_loans_list"];
        put?: never;
        /** @description GET/POST /api/funds/{fund_pk}/loans/ */
        post: operations["funds_loans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funds/{fund_pk}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/POST /api/funds/{fund_pk}/members/ — list and add members to a fund. */
        get: operations["funds_members_list"];
        put?: never;
        /** @description GET/POST /api/funds/{fund_pk}/members/ — list and add members to a fund. */
        post: operations["funds_members_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funds/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `/api/funds/` -- list/create, and `/api/funds/{id}/` -- retrieve/update/delete.
         *
         *     Every action is scoped to funds the caller created: `get_queryset`
         *     (via `FundOwnedQuerySetMixin`) filters the list, and `creator` is
         *     stamped from the request on create, never accepted from the client.
         */
        get: operations["funds_retrieve"];
        /**
         * @description `/api/funds/` -- list/create, and `/api/funds/{id}/` -- retrieve/update/delete.
         *
         *     Every action is scoped to funds the caller created: `get_queryset`
         *     (via `FundOwnedQuerySetMixin`) filters the list, and `creator` is
         *     stamped from the request on create, never accepted from the client.
         */
        put: operations["funds_update"];
        post?: never;
        /**
         * @description `/api/funds/` -- list/create, and `/api/funds/{id}/` -- retrieve/update/delete.
         *
         *     Every action is scoped to funds the caller created: `get_queryset`
         *     (via `FundOwnedQuerySetMixin`) filters the list, and `creator` is
         *     stamped from the request on create, never accepted from the client.
         */
        delete: operations["funds_destroy"];
        options?: never;
        head?: never;
        /**
         * @description `/api/funds/` -- list/create, and `/api/funds/{id}/` -- retrieve/update/delete.
         *
         *     Every action is scoped to funds the caller created: `get_queryset`
         *     (via `FundOwnedQuerySetMixin`) filters the list, and `creator` is
         *     stamped from the request on create, never accepted from the client.
         */
        patch: operations["funds_partial_update"];
        trace?: never;
    };
    "/api/funds/{id}/reports/monthly/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/funds/{id}/reports/monthly/?period_start=YYYY-MM-DD */
        get: operations["funds_reports_monthly_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/loans/{id}/ */
        get: operations["loans_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description PATCH /api/members/{id}/ and PUT /api/members/{id}/cards/. */
        patch: operations["members_partial_update"];
        trace?: never;
    };
    "/api/members/{id}/adjustments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description PATCH /api/members/{id}/ and PUT /api/members/{id}/cards/. */
        post: operations["members_adjustments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{id}/cards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description PATCH /api/members/{id}/ and PUT /api/members/{id}/cards/. */
        put: operations["members_cards_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{id}/settle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description PATCH /api/members/{id}/ and PUT /api/members/{id}/cards/. */
        post: operations["members_settle_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{id}/wallet/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description PATCH /api/members/{id}/ and PUT /api/members/{id}/cards/. */
        get: operations["members_wallet_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            access: string;
        };
        BankTransaction: {
            readonly id: number;
            readonly fund: number;
            /** Format: int64 */
            amount: number;
            /** Format: date-time */
            transfer_datetime: string;
            tracking_code?: string;
            from_card: string;
            note?: string;
            readonly matched_member: number | null;
            readonly wallet_charged: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        Fund: {
            readonly id: number;
            name: string;
            readonly creator: number;
            monthly_share_amount: number;
            default_loan_amount: number;
            default_installment_count: number;
            contribution_day: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Installment: {
            readonly id: number;
            readonly installment_number: number | null;
            /** Format: date */
            readonly due_date: string;
            readonly amount: number;
            readonly status: components["schemas"]["InstallmentStatusEnum"];
            /** Format: date-time */
            readonly paid_at: string | null;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `PAID` - Paid
         * @enum {string}
         */
        InstallmentStatusEnum: "PENDING" | "PAID";
        Loan: {
            readonly id: number;
            readonly member: number;
            readonly fund: number;
            /** Format: int64 */
            loan_amount: number;
            installment_count: number;
            installments_to_generate: number;
            /** Format: date */
            issue_date: string;
            readonly status: components["schemas"]["LoanStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            readonly installments: components["schemas"]["Installment"][];
        };
        /**
         * @description * `ACTIVE` - Active
         *     * `COMPLETED` - Completed
         * @enum {string}
         */
        LoanStatusEnum: "ACTIVE" | "COMPLETED";
        Member: {
            readonly id: number;
            readonly user: number;
            readonly user_phone: string;
            readonly user_full_name: string;
            readonly fund: number;
            share_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedBankTransactionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["BankTransaction"][];
        };
        PaginatedFundList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Fund"][];
        };
        PaginatedLoanList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Loan"][];
        };
        PaginatedMemberList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Member"][];
        };
        PatchedFund: {
            readonly id?: number;
            name?: string;
            readonly creator?: number;
            monthly_share_amount?: number;
            default_loan_amount?: number;
            default_installment_count?: number;
            contribution_day?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedMember: {
            readonly id?: number;
            readonly user?: number;
            readonly user_phone?: string;
            readonly user_full_name?: string;
            readonly fund?: number;
            share_count?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        Register: {
            readonly id: number;
            phone: string;
            full_name?: string;
            password: string;
        };
        ReversalRequest: {
            /** @default  */
            description: string;
        };
        TokenObtainPair: {
            phone: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        User: {
            readonly id: number;
            readonly phone: string;
            readonly full_name: string;
            /** Format: date-time */
            readonly date_joined: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    bank_transactions_assign_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this bank transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["BankTransaction"];
                "multipart/form-data": components["schemas"]["BankTransaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
        };
    };
    bank_transactions_rematch_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this bank transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["BankTransaction"];
                "multipart/form-data": components["schemas"]["BankTransaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
        };
    };
    dues_reverse_payment_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReversalRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReversalRequest"];
                "multipart/form-data": components["schemas"]["ReversalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReversalRequest"];
                };
            };
        };
    };
    funds_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFundList"];
                };
            };
        };
    };
    funds_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Fund"];
                "application/x-www-form-urlencoded": components["schemas"]["Fund"];
                "multipart/form-data": components["schemas"]["Fund"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fund"];
                };
            };
        };
    };
    funds_bank_transactions_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBankTransactionList"];
                };
            };
        };
    };
    funds_bank_transactions_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["BankTransaction"];
                "multipart/form-data": components["schemas"]["BankTransaction"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
        };
    };
    funds_bank_transactions_import_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["BankTransaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
        };
    };
    funds_bank_transactions_unmatched_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
        };
    };
    funds_loans_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLoanList"];
                };
            };
        };
    };
    funds_loans_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Loan"];
                "application/x-www-form-urlencoded": components["schemas"]["Loan"];
                "multipart/form-data": components["schemas"]["Loan"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
        };
    };
    funds_members_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMemberList"];
                };
            };
        };
    };
    funds_members_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Member"];
                "application/x-www-form-urlencoded": components["schemas"]["Member"];
                "multipart/form-data": components["schemas"]["Member"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    funds_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this fund. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fund"];
                };
            };
        };
    };
    funds_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this fund. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Fund"];
                "application/x-www-form-urlencoded": components["schemas"]["Fund"];
                "multipart/form-data": components["schemas"]["Fund"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fund"];
                };
            };
        };
    };
    funds_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this fund. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    funds_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this fund. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedFund"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedFund"];
                "multipart/form-data": components["schemas"]["PatchedFund"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fund"];
                };
            };
        };
    };
    funds_reports_monthly_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this fund. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fund"];
                };
            };
        };
    };
    loans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
        };
    };
    members_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMember"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMember"];
                "multipart/form-data": components["schemas"]["PatchedMember"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    members_adjustments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Member"];
                "application/x-www-form-urlencoded": components["schemas"]["Member"];
                "multipart/form-data": components["schemas"]["Member"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    members_cards_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Member"];
                "application/x-www-form-urlencoded": components["schemas"]["Member"];
                "multipart/form-data": components["schemas"]["Member"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    members_settle_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Member"];
                "application/x-www-form-urlencoded": components["schemas"]["Member"];
                "multipart/form-data": components["schemas"]["Member"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    members_wallet_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
